version: '3.7'

services:
  customs_server_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - '3001:3001'
  customs_server_test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: 'yarn test'
